name: YouTube Video Botu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Zorla Yükle
        run: |
          python -m pip install --upgrade pip
          # Hem dosyadan hem manuel olarak kütüphaneleri kuruyoruz
          pip install moviepy==1.0.3 edge-tts requests

      - name: Botu Çalıştır
        run: python main.py

      - name: Videoyu Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: cizgi-film-videosu
          path: ilk_cizgi_filmim.mp4
