name: Botu Calistir
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kutuphaneleri Yukle
        run: pip install google-generativeai
      - name: Botu Tetikle
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: python main.py
